close all
clear all

% Put all your file locations here
% Output will save image in same folder as file locations with same name


filenames = {%'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_1_MPH_90.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_5_MPH_90.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_6_MPH_83.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_7_MPH_85.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_8_MPH_99.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_9_MPH_87.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_10_MPH_109.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_11_MPH_93.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_12_MPH_94.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_13_MPH_97.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_14_MPH_95.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_15_MPH_96.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_16_MPH_86.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_17_MPH_82.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_18_MPH_80.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_19_MPH_95.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_20_MPH_86.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_21_MPH_91.mp4'; ...
% 'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Serena_Williams_US_OPEN/Serena_Clip_22_MPH_84.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_1_MPH_96.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_2_MPH_128.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_3_MPH_121.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_4_MPH_128.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_5_MPH_111.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_6_MPH_116.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_7_MPH_127.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_8_MPH_108.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_9_MPH_130.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_10_MPH_106.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_11_MPH_128.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_12_MPH_117.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_13_MPH_99.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_14_MPH_87.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_15_MPH_93.mp4'; ...
'Tennis_Ball_Tracking/Tennis_Ball_Project/Tennis_Rally_Clips/Borna Gojo vs Jiri Vesely/Vesely_Clip_16_MPH_127.mp4'; ...
            };
frame_rate = 30;

for i=1:length(filenames)
    filename = filenames{i};
    tennis_ball_main(filename,frame_rate)
end